"""Derive DAG node content from scenario run records.

Reads each scenario's golden run record and its manifest ``dag.node_bindings``,
fills the label/desc templates from the run's ``facts``, and writes a single
generated overlay: ``user_stories/dag/userstory_dag_derived.yaml``.

``story_components.build_node_index`` merges this overlay over the hand-authored
``userstory_dag_data.yaml`` (overlay wins for bound nodes' label/desc), so the
DAG shown on the site always reflects the real run output.  The base YAML — with
its comments and anchors — is never rewritten.

CLI::

    python -m scenarios.harness.derive_dag            # all scenarios
    python -m scenarios.harness.derive_dag US-2b.1    # one scenario
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any

import yaml

from .manifest import REPO_ROOT, Manifest, all_manifests, load_manifest

DERIVED_FILE = REPO_ROOT / "user_stories" / "dag" / "userstory_dag_derived.yaml"


def _fill(template: str, facts: dict[str, Any]) -> str:
    try:
        return template.format(**facts)
    except KeyError as e:
        raise KeyError(
            f"DAG binding template {template!r} references unknown fact {e}. "
            f"Available facts: {sorted(facts)}"
        )


def derive_nodes_for(manifest: Manifest) -> dict[str, dict[str, str]]:
    """Return ``{node_id: {label, desc}}`` for one scenario, or {} if no run."""
    if not manifest.run_record_path.exists():
        print(
            f"  (skip {manifest.id}: no run record at "
            f"{manifest.run_record_path.name} — run the harness first)",
            file=sys.stderr,
        )
        return {}
    record = json.loads(manifest.run_record_path.read_text())
    facts = record["facts"]
    bindings = manifest.dag.get("node_bindings", {})
    nodes: dict[str, dict[str, str]] = {}
    for node_id, binding in bindings.items():
        entry: dict[str, str] = {}
        if "label" in binding:
            entry["label"] = _fill(binding["label"], facts)
        if "desc" in binding:
            entry["desc"] = _fill(binding["desc"], facts)
        if entry:
            nodes[node_id] = entry
    return nodes


def derive(manifests: list[Manifest]) -> dict[str, Any]:
    nodes: dict[str, dict[str, str]] = {}
    generated_from: dict[str, str] = {}
    for m in manifests:
        m_nodes = derive_nodes_for(m)
        if not m_nodes:
            continue
        # Later scenarios overriding the same node would clash; warn instead.
        for nid, entry in m_nodes.items():
            if nid in nodes and nodes[nid] != entry:
                print(
                    f"  WARNING: node {nid} bound by multiple scenarios with "
                    f"different content; {m.id} wins.",
                    file=sys.stderr,
                )
            nodes[nid] = entry
        generated_from[m.id] = m.run_record_path.name
    return {"nodes": nodes, "generated_from": generated_from}


def write_overlay(overlay: dict[str, Any]) -> None:
    header = (
        "# =============================================================\n"
        "# GENERATED by scenarios/harness/derive_dag.py — DO NOT EDIT.\n"
        "# DAG node label/desc derived from real scenario run records.\n"
        "# Regenerate: python -m scenarios.harness.derive_dag\n"
        "# =============================================================\n"
    )
    DERIVED_FILE.write_text(
        header
        + yaml.safe_dump(overlay, sort_keys=True, default_flow_style=False)
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "scenario", nargs="?", help="Scenario id (default: all)"
    )
    args = parser.parse_args(argv)

    manifests = (
        [load_manifest(args.scenario)] if args.scenario else all_manifests()
    )
    overlay = derive(manifests)
    write_overlay(overlay)
    print(
        f"Wrote {len(overlay['nodes'])} derived node(s) from "
        f"{len(overlay['generated_from'])} scenario(s) -> {DERIVED_FILE}"
    )
    for nid, entry in sorted(overlay["nodes"].items()):
        lbl = entry.get("label", "").replace("\n", "\\n")
        print(f"  {nid}: {lbl!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
