"""E2E test for stitching the US-2b.1 full-path video.

Validates that all prerequisite segments exist, then runs
stitch_full_path.py to produce 2b1_full_path.mp4 with merged markers
covering every node in the full DAG path.
"""

import json
from test.gif.gif_test_helpers import (
    get_demo_env,
    get_project_root,
    run_demo_script,
)

import pytest

# Expected marker IDs in the stitched video, in temporal order.
EXPECTED_MARKERS = [
    # From cfg_1b1w segment (1a_setup_config)
    "acct_triodos_csv",
    "acct_eur_wallet",
    "dirp_default",
    "fnames_default",
    "catcfg_default",
    "malgo_default",
    # From cat_basic segment (1b_add_category)
    "cat_basic__groceries",
    "cat_basic__withdrawl",
    # From starting_journal segment (2b_data_files)
    "start_2024_1000eur",
    # From bank_csv segment (2b_data_files)
    "csv_ekoplaza_4217_jan15",
    # From receipt segment (2b_label_receipt)
    "img_ekoplaza_card",
    "lbl_ekoplaza_card_eur",
    # From journal_output segment (2b_data_files)
    "jrnl_groceries_ekoplaza",
]

# Prerequisite segment MP4s that must exist before stitching.
PREREQUISITE_SEGMENTS = [
    "1a_setup_config/output/cfg_1b1w.mp4",
    "1b_add_category/output/cat_basic.mp4",
    "2b_data_files/output/starting_journal.mp4",
    "2b_data_files/output/bank_csv.mp4",
    "2b_label_receipt/output/2b_label_receipt.mp4",
    "2b_data_files/output/journal_output.mp4",
]


def test_stitch_2b1_full_path(temp_finance_root, monkeypatch):
    """Test stitching all segments into 2b1_full_path.mp4 with merged markers."""
    project_root = get_project_root()
    monkeypatch.chdir(project_root)

    gifs_root = project_root / "gifs"

    # Check prerequisites exist (they should be generated by prior tests
    # or by running generate.sh scripts)
    missing = []
    for seg in PREREQUISITE_SEGMENTS:
        if not (gifs_root / seg).exists():
            missing.append(seg)

    if missing:
        pytest.skip(
            "Missing prerequisite segments (run segment tests first): "
            f"{missing}"
        )

    # Run the stitch via generate.sh with SKIP_STITCH=0
    gifs_root / "2b_label_receipt" / "generate.sh"
    env = get_demo_env()
    # Override: enable stitching, skip the TUI recording (it already exists)
    env["SKIP_STITCH"] = "0"
    # Skip the recording step by making run_full_pipeline a no-op.
    # We do this by calling stitch_full_path.py directly instead.
    stitch_result = run_demo_script(
        script_path=project_root / "gifs" / "2b_label_receipt" / "generate.sh",
        env=env,
        config_path=temp_finance_root["config_path"],
        timeout=180,
    )

    # If the full generate.sh failed (e.g. TUI recording issue), run stitch directly
    if stitch_result.returncode != 0:
        import subprocess
        import sys

        stitch_env = env.copy()
        stitch_env["PYTHONPATH"] = str(project_root)
        segments = [str(gifs_root / s) for s in PREREQUISITE_SEGMENTS]
        output = str(
            gifs_root / "2b_label_receipt" / "output" / "2b1_full_path.mp4"
        )

        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "gifs.automation.stitch_full_path",
                "--segments",
                *segments,
                "--output",
                output,
            ],
            capture_output=True,
            text=True,
            timeout=60,
            env=stitch_env,
        )
        assert result.returncode == 0, f"Stitch failed: {result.stderr}"

    # Verify output
    full_path_mp4 = (
        gifs_root / "2b_label_receipt" / "output" / "2b1_full_path.mp4"
    )
    assert full_path_mp4.exists(), "Stitched MP4 should exist"
    assert full_path_mp4.stat().st_size > 10_000, "MP4 should not be empty"

    # Verify merged markers JSON
    markers_json = (
        gifs_root / "2b_label_receipt" / "output" / "2b1_full_path_markers.json"
    )
    assert markers_json.exists(), "Merged markers JSON should exist"

    data = json.loads(markers_json.read_text())
    markers = data["markers"]

    # All expected markers must be present
    for marker_id in EXPECTED_MARKERS:
        assert marker_id in markers, (
            f"Marker {marker_id} missing from stitched markers. "
            f"Found: {sorted(markers.keys())}"
        )

    # Timestamps must be monotonically non-decreasing
    ts_values = [markers[k] for k in EXPECTED_MARKERS if k in markers]
    for i in range(len(ts_values) - 1):
        assert ts_values[i] <= ts_values[i + 1], (
            f"Timestamps not monotonic: {EXPECTED_MARKERS[i]}={ts_values[i]} > "
            f"{EXPECTED_MARKERS[i+1]}={ts_values[i+1]}"
        )

    # Total duration must be sum of segments (approximately)
    assert (
        data["total_duration"] > 100.0
    ), f"Total duration should be > 100s, got {data['total_duration']}"

    # Segments list should have 6 entries
    assert (
        len(data["segments"]) == 6
    ), f"Should have 6 segments, got {len(data['segments'])}"
